version: '2'
services:
    jhipsterinnovate-app:
        image: jhipsterinnovate
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipsterinnovate-mysql:3306/jhipsterinnovate?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipsterinnovate-mysql:
        extends:
            file: mysql.yml
            service: jhipsterinnovate-mysql
